apiVersion: v1
kind: ConfigMap
metadata:
  name: microservice-b-configmap
  labels:
    name: microservice-b-configmap
data:
  env: |
      RABBITMQ_DEFAULT_HOST=localhost
      RABBITMQ_DEFAULT_PORT=5672
      RABBITMQ_DEFAULT_VHOST=/
      RABBITMQ_CONSUMER_NAME=payment-ms2222
      RABBITMQ_CONSUMER_QUEUE_NAME=orders
      RABBITMQ_NOTIFICATION_EX=amq.direct
      RABBITMQ_NOTIFICATION_ROUTING_KEY=
      RABBITMQ_DLX=dlx